export const LAUNCHER_ABI = [
  {
    type: "error",
    name: "PoolAlreadyInitialized",
    inputs: [],
  },
  {
    type: "error",
    name: "TokenAlreadyExists",
    inputs: [],
  },
  {
    type: "error",
    name: "TokenNotBelowPair",
    inputs: [],
  },
  {
    type: "function",
    name: "launch",
    stateMutability: "payable",
    inputs: [
      {
        name: "p",
        type: "tuple",
        components: [
          { name: "name", type: "string" },
          { name: "symbol", type: "string" },
          { name: "metadataURI", type: "string" },
          { name: "salt", type: "bytes32" },
          { name: "floorTick", type: "int24" },
          { name: "pairedAsset", type: "address" },
          { name: "feeTier", type: "uint24" },
          { name: "firstBuyPairIn", type: "uint256" },
          { name: "minFirstBuyTokensOut", type: "uint256" },
        ],
      },
    ],
    outputs: [
      { name: "token", type: "address" },
      { name: "feeVault", type: "address" },
    ],
  },
  {
    type: "function",
    name: "predictTokenAddress",
    stateMutability: "view",
    inputs: [
      { name: "creator", type: "address" },
      { name: "salt", type: "bytes32" },
      { name: "name", type: "string" },
      { name: "symbol", type: "string" },
      { name: "metadataURI", type: "string" },
    ],
    outputs: [{ name: "token", type: "address" }],
  },
  {
    type: "function",
    name: "launchConfigHash",
    stateMutability: "view",
    inputs: [
      { name: "creator", type: "address" },
      {
        name: "p",
        type: "tuple",
        components: [
          { name: "name", type: "string" },
          { name: "symbol", type: "string" },
          { name: "metadataURI", type: "string" },
          { name: "salt", type: "bytes32" },
          { name: "floorTick", type: "int24" },
          { name: "pairedAsset", type: "address" },
          { name: "feeTier", type: "uint24" },
          { name: "firstBuyPairIn", type: "uint256" },
          { name: "minFirstBuyTokensOut", type: "uint256" },
        ],
      },
      { name: "nativeValue", type: "uint256" },
    ],
    outputs: [{ name: "configHash", type: "bytes32" }],
  },
  {
    type: "function",
    name: "launchProvenance",
    stateMutability: "view",
    inputs: [{ name: "token", type: "address" }],
    outputs: [
      { name: "configHash", type: "bytes32" },
      { name: "launchedAt", type: "uint64" },
      { name: "firstBuyAmountIn", type: "uint256" },
      { name: "firstBuyAmountOut", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "tokenFactory",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "factory", type: "address" }],
  },
  {
    type: "function",
    name: "protocolTreasury",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "treasury", type: "address" }],
  },
  {
    type: "function",
    name: "tokenInitCodeHash",
    stateMutability: "view",
    inputs: [
      { name: "name", type: "string" },
      { name: "symbol", type: "string" },
      { name: "metadataURI", type: "string" },
      { name: "creator", type: "address" },
    ],
    outputs: [{ name: "initCodeHash", type: "bytes32" }],
  },
  {
    type: "function",
    name: "tokenCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "count", type: "uint256" }],
  },
  {
    type: "function",
    name: "launchedTokens",
    stateMutability: "view",
    inputs: [
      { name: "offset", type: "uint256" },
      { name: "limit", type: "uint256" },
    ],
    outputs: [{ name: "tokens", type: "address[]" }],
  },
  {
    type: "function",
    name: "launches",
    stateMutability: "view",
    inputs: [{ name: "token", type: "address" }],
    outputs: [
      { name: "exists", type: "bool" },
      { name: "creator", type: "address" },
      { name: "pool", type: "address" },
      { name: "feeVault", type: "address" },
      { name: "positionId", type: "uint256" },
      { name: "pairedAsset", type: "address" },
      { name: "feeTier", type: "uint24" },
      { name: "floorTick", type: "int24" },
    ],
  },
  {
    type: "event",
    name: "TokenLaunched",
    inputs: [
      { name: "token", type: "address", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "feeVault", type: "address", indexed: true },
      { name: "pool", type: "address", indexed: false },
      { name: "name", type: "string", indexed: false },
      { name: "symbol", type: "string", indexed: false },
      { name: "metadataURI", type: "string", indexed: false },
      { name: "positionId", type: "uint256", indexed: false },
      { name: "pairedAsset", type: "address", indexed: false },
      { name: "feeTier", type: "uint24", indexed: false },
      { name: "floorTick", type: "int24", indexed: false },
    ],
  },
  {
    type: "event",
    name: "LaunchProvenanceRecorded",
    inputs: [
      { name: "token", type: "address", indexed: true },
      { name: "configHash", type: "bytes32", indexed: true },
      { name: "launchedAt", type: "uint64", indexed: false },
      { name: "firstBuyAmountIn", type: "uint256", indexed: false },
      { name: "firstBuyAmountOut", type: "uint256", indexed: false },
    ],
  },
] as const;

export const FEE_VAULT_ABI = [
  {
    type: "function",
    name: "transfer",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "value", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "claimAll",
    stateMutability: "nonpayable",
    inputs: [{ name: "to", type: "address" }],
    outputs: [
      { name: "launchAmount", type: "uint256" },
      { name: "pairAmount", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "harvest",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [
      { name: "launchAmount", type: "uint256" },
      { name: "pairAmount", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "claimableAll",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "assets", type: "address[]" },
      { name: "amounts", type: "uint256[]" },
    ],
  },
  {
    type: "function",
    name: "revenueAssets",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "assets", type: "address[]" }],
  },
  {
    type: "function",
    name: "totalSupply",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

export const ERC20_ABI = [
  {
    type: "function",
    name: "name",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "symbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "totalSupply",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "transfer",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "value", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
] as const;
